"""message

Revision ID: a8cde22f1f30
Revises: 0b397bedc972
Create Date: 2025-09-28 22:11:20.935198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cde22f1f30'
down_revision = '0b397bedc972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
